PineconWeb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from pinecon import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("pinecon.urls", namespace="pinecon")),
]

pinecon/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^register$', views.register, name='register'),
    url(r'^home', views.home, name='home'),
    url(r'^login', auth_views.login, {"template_name": "pinecon/login.html"}, name='login'),
    url(r'^logout/$', auth_views.logout, {"next_page": "/login"}, name='logout'),

    url(r'^task/', include('pinecon.urlpatterns.task_urls')),
    url(r'^plan/', include('pinecon.urlpatterns.plan_urls')),
    url(r'^group/', include('pinecon.urlpatterns.group_urls')),
    url(r'^date/', include('pinecon.urlpatterns.date_urls')),

    url(r"^get_executors/$", views.get_executors, name="get_executors"),
]

pinecon/library/models/helpers.py
""" This module contains common things for several models. """

NO = "no"
YES = "yes"

pinecon/models.py
from django.db import models

# Create your models here.

pinecon/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ValidationError
from django.contrib.auth.forms import UserCreationForm

from pinecon import get_service
from pinecon.library.models import helpers
from pinecon.library.models.model.plan import PlanRepetitionStyle, PlanEndReason
from pinecon.library.models.model.task import TaskPriority, TaskStatus
from pinecon.library.models.model.task_date import TaskDateType

DEFAULT_EMPTY_LABEL = ("Choose Year", "Choose Month", "Choose Day")


class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class TaskForm(forms.Form):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'class': 'input'}))
    priority = forms.ChoiceField(choices=[(priority.value, priority.value) for priority in TaskPriority],
                                 initial=TaskPriority.MID.value)
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}), required=False)
    status = forms.ChoiceField(choices=[(status.value, status.value) for status in TaskStatus],
                               required=False)

    start_date = forms.DateField(widget=forms.SelectDateWidget(empty_label=DEFAULT_EMPTY_LABEL), required=False)
    end_date = forms.DateField(widget=forms.SelectDateWidget(empty_label=DEFAULT_EMPTY_LABEL), required=False)

    def clean_date(self):
        form_data = self.cleaned_data
        start_date = form_data.get("start_date", None)
        end_date = form_data.get("end_date", None)
        if start_date is not None and end_date is not None:
            if end_date < start_date:
                raise ValidationError("End date sooner than start date")
        return start_date, end_date

    def clean_start_date(self):
        start_date, _ = self.clean_date()
        return start_date

    def clean_end_date(self):
        _, end_date = self.clean_date()
        return end_date


class DateForm(forms.Form):
    date = forms.DateField(widget=forms.SelectDateWidget,
                           initial=datetime.now().date())
    date_type = forms.ChoiceField(choices=[(date_type.value, date_type.value) for date_type in TaskDateType],
                                  initial=TaskDateType.EVENT.value)


class GroupForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)

        user_tasks = get_service().get_checked_filtered_tasks(creator_id=user.user_id)
        executor_tasks = get_service().get_checked_filtered_tasks(executor_id=user.user_id)
        tasks = user_tasks + list(set(executor_tasks) - set(user_tasks))

        self.fields["tasks"].choices = [(task.task_id, task.title) for task in tasks]

    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'class': 'input'}))
    tasks = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(attrs={'class': 'select_multiple'}), required=False)


class PlanForm(forms.Form):
    repetition_style = forms.ChoiceField(choices=[(repetition_style.value, repetition_style.value)
                                                  for repetition_style in PlanRepetitionStyle],
                                         initial=PlanRepetitionStyle.DAILY.value)

    end_reason = forms.ChoiceField(choices=[(end_reason.value, end_reason.value) for end_reason in PlanEndReason],
                                   label="End Reason",
                                   initial=PlanEndReason.NEVER.value)

    interval_counter = forms.IntegerField(widget=forms.NumberInput, min_value=1, initial=1,
                                          label="Number of basic intervals")

    start_date = forms.DateField(
        widget=forms.SelectDateWidget,
        label="Task will begin on this day",
        initial=datetime.now().date())

    end_date = forms.DateField(widget=forms.SelectDateWidget(empty_label=DEFAULT_EMPTY_LABEL), required=False,
                               label="Task will be completed by this date")

    repetitions_count = forms.IntegerField(widget=forms.NumberInput, min_value=1, required=False,
                                           label="Number of times this task will be created")

    is_active = forms.ChoiceField(choices=[(helpers.NO, helpers.NO),
                                           (helpers.YES, helpers.YES)],
                                  required=False)

    def clean_repetitions_count(self):
        form_data = self.cleaned_data
        end_reason = form_data["end_reason"]
        repetitions_count = form_data.get("repetitions_count", None)

        if end_reason == PlanEndReason.AFTER_NUMBER_OF_TIMES.value and repetitions_count is None:
            raise ValidationError("Enter repetitions count")

        return repetitions_count

    def clean_start_date(self):
        form_data = self.cleaned_data
        start_date = form_data["start_date"]

        if start_date < datetime.now().date():
            raise ValidationError("Start date cannot be in the past")

        return start_date

    def clean_end_date(self):
        form_data = self.cleaned_data
        end_reason = form_data["end_reason"]
        end_date = form_data.get("end_date", None)

        if end_reason == PlanEndReason.AFTER_DATE.value and end_date is None:
            raise ValidationError("Choose end date")

        if end_date:
            start_date = form_data["start_date"]
            if end_date < start_date:
                raise ValidationError("End date sooner than start date")

        return end_date

pinecon/views.py
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.decorators import login_required
from django.forms import HiddenInput
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect

from pinecon import get_service
from pinecon.forms import TaskForm, DateForm, GroupForm, PlanForm, UserCreateForm
from pinecon.library.models.model.executor_to_task import ExecutorToTaskRelation
from pinecon.library.models.model.group import Group
from pinecon.library.models.model.group_to_task import GroupToTaskRelation
from pinecon.library.models.model.plan import PlanEndReason, Plan
from pinecon.library.models.model.task import TaskStatus, Task, TaskType
from pinecon.library.models.model.task_date import TaskDate, TaskDateType
from pinecon.library.models.model.task_to_task import TaskToTaskRelation
from pinecon.library.models.model.user import User
from pinecon.library.services.exceptions import PineconException


def login(request):
    username = request.user.username
    user = get_service().get_checked_user_by_username(username)
    get_service().current_user_id = user.user_id
    return user


def register(request):
    if request.method == "POST":
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            data = form.cleaned_data
            username = data["username"]
            password = data["password1"]
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            get_service().add_checked_user(User(user.username, user.id))
            return HttpResponseRedirect(reverse("pinecon:home"))
    else:
        form = UserCreateForm()

    context = {"form": form}
    return render(request=request, template_name="pinecon/register.html", context=context)


@login_required(login_url="/login")
def home(request):
    user = login(request)

    all_tasks = get_service().get_checked_filtered_tasks(creator_id=user.user_id, type=TaskType.SIMPLE.value)
    plans = get_service().get_checked_plan(user_id=user.user_id)
    template_tasks = get_service().get_checked_filtered_tasks(creator_id=user.user_id, type=TaskType.PLAN.value)

    plans_and_templates = list(zip(plans, template_tasks))

    groups = get_service().get_checked_filtered_groups(creator_id=user.user_id)
    executor_tasks = get_service().get_checked_filtered_tasks(executor_id=user.user_id)
    overdue_tasks = get_service().get_checked_filtered_tasks(creator_id=user.user_id,
                                                             status=TaskStatus.OVERDUE.value)
    finished_tasks = get_service().get_checked_filtered_tasks(creator_id=user.user_id,
                                                              status=TaskStatus.EXECUTED.value)

    tasks = list(set(all_tasks) - set(finished_tasks) - set(overdue_tasks))

    context = {
        "tasks": tasks,
        "plans_and_templates": plans_and_templates,
        "groups": groups,
        "executor_tasks": executor_tasks,
        "overdue_tasks": overdue_tasks,
        "finished_tasks": finished_tasks,
    }

    get_service().update_application()

    return render(request=request, template_name="pinecon/home.html", context=context)


@login_required(login_url="/login")
def create_task(request):
    user = login(request)

    if request.method == "POST":
        task_form = TaskForm(request.POST)
        if task_form.is_valid():
            data = task_form.cleaned_data

            task = get_service().add_checked_task(Task(creator_id=user.user_id,
                                                       title=data["title"],
                                                       priority=data["priority"],
                                                       description=data["description"]))

            end_date = data["end_date"]
            start_date = data["start_date"]
            if end_date and start_date:
                get_service().add_checked_date(TaskDate(task.task_id, TaskDateType.START.value, start_date))
                get_service().add_checked_date(TaskDate(task.task_id, TaskDateType.END.value, end_date))
            elif end_date:
                get_service().add_checked_date(TaskDate(task.task_id, TaskDateType.END.value, end_date))
            elif start_date:
                get_service().add_checked_date(TaskDate(task.task_id, TaskDateType.EVENT.value, start_date))

            return HttpResponseRedirect(reverse("pinecon:home"))
    else:
        task_form = TaskForm()

    task_form.fields["status"].widget = HiddenInput()

    context = {"form": task_form}
    return render(request=request, template_name="pinecon/task/create.html", context=context)


@login_required(login_url="/login")
def show_task(request, task_id):
    user = login(request)

    task = get_service().get_checked_task_by_id(task_id)

    plan = None
    if task.task_type == TaskType.PLAN.value:
        plan = get_service().get_checked_filtered_plans(task_id=task_id)[0]

    task_dates = get_service().get_all_checked_task_dates(task_id=task_id)

    task_groups = get_service().get_checked_filtered_groups(creator_id=user.user_id,
                                                       task_id=task_id)

    task_executors = get_service().get_checked_executors(task_id=task_id)
    task_creator = get_service().is_creator(executor_id=user.user_id, task_id=task_id)
    print(task_creator)
    context = {
        "task": task,
        "plan": plan,
        "dates": task_dates,
        "groups": task_groups,
        "executors": task_executors,
        "creator": task_creator
    }

    return render(request=request, template_name="pinecon/task/show.html", context=context)


@login_required(login_url="/login")
def update_task(request, task_id):
    login(request)

    task = get_service().get_checked_task_by_id(task_id)

    if request.method == 'POST':
        task_form = TaskForm(request.POST)
        if task_form.is_valid():
            data = task_form.cleaned_data

            get_service().update_checked_task(task_id=task_id,
                                              title=data["title"],
                                              priority=data["priority"],
                                              description=data["description"],
                                              status=data["status"])

            return HttpResponseRedirect(reverse('pinecon:show_task', args=(task_id,)))
    else:
        task_form = TaskForm(initial={
            "title": task.title,
            "priority": task.priority,
            "description": task.description,
            "status": task.status
        })

        task_form.fields["start_date"].widget = HiddenInput()
        task_form.fields["end_date"].widget = HiddenInput()

        if task.task_type == TaskType.PLAN.value:
            task_form.fields["status"].widget = HiddenInput()
        elif task.status == TaskStatus.CREATED.value:
            choices = [(status.value, status.value) for status in TaskStatus]
            choices.remove((TaskStatus.DEFINED.value, TaskStatus.DEFINED.value))
            task_form.fields["status"].choices = choices
        else:
            choices = [(status.value, status.value) for status in TaskStatus]
            choices.remove((TaskStatus.DEFINED.value, TaskStatus.DEFINED.value))
            choices.remove((TaskStatus.CREATED.value, TaskStatus.CREATED.value))
            task_form.fields["status"].choices = choices

    context = {
        "form": task_form,
        "task_id": task_id
    }

    return render(request=request, template_name="pinecon/task/update.html", context=context)


@login_required(login_url="/login")
def finish_task(request, task_id):
    login(request)

    get_service().update_checked_task(task_id, status='executed')

    return HttpResponseRedirect(reverse("pinecon:home"))


@login_required(login_url="/login")
def delete_task(request, task_id):
    login(request)

    get_service().delete_checked_task_with_relations(task_id)

    return HttpResponseRedirect(reverse("pinecon:home"))


@login_required(login_url="/login")
def create_subtask(request, task_id):
    context = {
        "task_id": task_id
    }

    return render(request=request, template_name="pinecon/task/subtask/create.html", context=context)


@login_required(login_url="/login")
def create_executor(request, task_id):
    login(request)

    task = get_service().get_checked_task_by_id(task_id)

    context = {
        "task": task
    }

    return render(request=request, template_name="pinecon/task/executor/create.html", context=context)


@login_required(login_url="/login")
def create_date(request, task_id):
    login(request)

    if request.method == "POST":
        date_form = DateForm(request.POST)
        if date_form.is_valid():
            try:
                data = date_form.cleaned_data

                date = get_service().add_checked_date(TaskDate(task_id=task_id,
                                                               date=data["date"],
                                                               date_type=data["date_type"]))
                return HttpResponseRedirect(reverse('pinecon:show_task', args=(date.task_id,)))

            except PineconException as exception:
                date_form.add_error('date', str(exception))

    else:
        date_form = DateForm()

    context = {
        "task_id": task_id,
        "form": date_form
    }

    return render(request=request, template_name="pinecon/date/create.html", context=context)


@login_required(login_url="/login")
def update_date(request, date_id):
    login(request)

    date = get_service().get_checked_date_by_id(date_id)

    if request.method == "POST":
        date_form = DateForm(request.POST)
        if date_form.is_valid():
            data = date_form.cleaned_data

pinecon/templates/pinecon/task/executor/create.html
{% extends 'pinecon/base.html' %}
{% block content %}
<div class="greeting__text_small">Select executor: </div>

<div class="search-form">
    <input class="search-form__input" id="input-filter" type="text" placeholder="Enter an executor, which will be work with this task...">
</div>
<div class="scrollpane">
    <ul id="users-list" class="select__ul"></ul>
</div>
<br/>
<div class="container__button">
    <button type="submit" class='basic_button' onclick="addExecutorToTaskRelation()">Add Executor</button>
    <form action="{% url 'pinecon:show_task' task.task_id%}">
        <button type="submit" class='basic_button'>Back</button>
    </form>
</div>

<script>

    const csrftoken = $.cookie('csrftoken');

    // For more information: https://docs.djangoproject.com/en/1.11/ref/csrf/
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    function reloadUsers() {
        $("#users-list").empty();
        let username = "{{ user.username }}";
        loadResults("{% url 'pinecon:get_executors' %}", username, addUsersToList);
    }

    function loadResults(url, username, success_function) {
        $.ajax({
            url: url,
            username: username,
            success: function(response) {
                success_function(response);
            }
        });
    }

    function addUsersToList(users){
        // Add loaded task to list (ul)
        const len = users.length;
        for (let i = 0; i < len; i++) {
            let user_ = users[i];
            // Create document structure for task list
            let li = document.createElement('li');
            let username = document.createTextNode(user_.username);
            li.id = user_.user_id;
            li.appendChild(username);
            document.getElementById("users-list").appendChild(li);
        }
    }

    $(document).ready(function() {
        reloadUsers()
    });

    let tasks_list = document.getElementById("users-list");

    tasks_list.addEventListener('click', handler);

    function handler(event) {
        let li_list = $("#users-list").children("li");
        for (let item of li_list)
            item.classList.remove('checked');
        event.target.classList.toggle('checked');
    }

    function getSelectedElement(){
        let li_list = $("#users-list").children("li");
        for (let item of li_list) {
            if(item.classList.contains('checked'))
                selected_item_id = item.id;
        }
        return selected_item_id
    }

    function isExecutorValid(user_id){
        if(user_id < 0){
            alert("Please, specify user!");
            return false;
        }
        return true;
    }

    function addExecutorToTaskRelation(){

        let user_id = getSelectedElement("users-list");
        if (!isExecutorValid(user_id)) return;

        $.ajax({
            method: "POST",
            url: "{% url 'pinecon:add_executor_to_task_relation' %}",
            data: {
                "task_id": {{ task.task_id }},
                "user_id": user_id,
            },
            username: '{{ user.username }}',
            success: function(response) {
                showUsers(response)
            },
            error: function (xhr, ajaxOptions, thrownError) {
                showError(xhr, ajaxOptions, thrownError)
            }
        });
    }

    function showUsers(response) {
        if(response.success){
                    location.href="{% url 'pinecon:show_task' task.task_id %}"
                }
                else{
                    alert(response.error)
                }
    }

    function showError(xhr, ajaxOptions, thrownError) {
        alert(xhr.status);
        alert(thrownError);
    }

    // Dynamic filter
    $('input').on('keypress keyup', function(){
    let value = $(this).val().toLowerCase();
    if (value !== '') {

      $('.select__ul > li').each(function () {
        if ($(this).text().toLowerCase().indexOf(value) > -1) {
          $(this).removeClass('displayNone');
        } else {
          $(this).addClass('displayNone');
        }
      });
    } else {
      $('.select__ul > li').removeClass('displayNone');
    }
});
</script>

{% endblock %}