PineconWeb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from pinecon import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("pinecon.urls", namespace="pinecon")),
]

pinecon/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^register$', views.register, name='register'),
    url(r'^home', views.home, name='home'),
    url(r'^login', auth_views.login, {"template_name": "pinecon/login.html"}, name='login'),
    url(r'^logout/$', auth_views.logout, {"next_page": "/login"}, name='logout'),

    url(r'^task/', include('pinecon.urlpatterns.task_urls')),
    url(r'^plan/', include('pinecon.urlpatterns.plan_urls')),
    url(r'^group/', include('pinecon.urlpatterns.group_urls')),
    url(r'^date/', include('pinecon.urlpatterns.date_urls')),

    url(r"^get_executors/$", views.get_executors, name="get_executors"),
]

pinecon/library/models/helpers.py
""" This module contains common things for several models. """

NO = "no"
YES = "yes"

pinecon/models.py
from django.db import models

# Create your models here.

pinecon/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ValidationError
from django.contrib.auth.forms import UserCreationForm

from pinecon import get_service
from pinecon.library.models import helpers
from pinecon.library.models.model.plan import PlanRepetitionStyle, PlanEndReason
from pinecon.library.models.model.task import TaskPriority, TaskStatus
from pinecon.library.models.model.task_date import TaskDateType

DEFAULT_EMPTY_LABEL = ("Choose Year", "Choose Month", "Choose Day")


class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class TaskForm(forms.Form):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'class': 'input'}))
    priority = forms.ChoiceField(choices=[(priority.value, priority.value) for priority in TaskPriority],
                                 initial=TaskPriority.MID.value)
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}), required=False)
    status = forms.ChoiceField(choices=[(status.value, status.value) for status in TaskStatus],
                               required=False)

    start_date = forms.DateField(widget=forms.SelectDateWidget(empty_label=DEFAULT_EMPTY_LABEL), required=False)
    end_date = forms.DateField(widget=forms.SelectDateWidget(empty_label=DEFAULT_EMPTY_LABEL), required=False)

    def clean_date(self):
        form_data = self.cleaned_data
        start_date = form_data.get("start_date", None)
        end_date = form_data.get("end_date", None)
        if start_date is not None and end_date is not None:
            if end_date < start_date:
                raise ValidationError("End date sooner than start date")
        return start_date, end_date

    def clean_start_date(self):
        start_date, _ = self.clean_date()
        return start_date

    def clean_end_date(self):
        _, end_date = self.clean_date()
        return end_date


class DateForm(forms.Form):
    date = forms.DateField(widget=forms.SelectDateWidget,
                           initial=datetime.now().date())
    date_type = forms.ChoiceField(choices=[(date_type.value, date_type.value) for date_type in TaskDateType],
                                  initial=TaskDateType.EVENT.value)


class GroupForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)

        user_tasks = get_service().get_checked_filtered_tasks(creator_id=user.user_id)
        executor_tasks = get_service().get_checked_filtered_tasks(executor_id=user.user_id)
        tasks = user_tasks + list(set(executor_tasks) - set(user_tasks))

        self.fields["tasks"].choices = [(task.task_id, task.title) for task in tasks]

    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'class': 'input'}))
    tasks = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(attrs={'class': 'select_multiple'}), required=False)


class PlanForm(forms.Form):
    repetition_style = forms.ChoiceField(choices=[(repetition_style.value, repetition_style.value)
                                                  for repetition_style in PlanRepetitionStyle],
                                         initial=PlanRepetitionStyle.DAILY.value)

    end_reason = forms.ChoiceField(choices=[(end_reason.value, end_reason.value) for end_reason in PlanEndReason],
                                   label="End Reason",
                                   initial=PlanEndReason.NEVER.value)

    interval_counter = forms.IntegerField(widget=forms.NumberInput, min_value=1, initial=1,
                                          label="Number of basic intervals")

    start_date = forms.DateField(
        widget=forms.SelectDateWidget,
        label="Task will begin on this day",
        initial=datetime.now().date())

    end_date = forms.DateField(widget=forms.SelectDateWidget(empty_label=DEFAULT_EMPTY_LABEL), required=False,
                               label="Task will be completed by this date")

    repetitions_count = forms.IntegerField(widget=forms.NumberInput, min_value=1, required=False,
                                           label="Number of times this task will be created")

    is_active = forms.ChoiceField(choices=[(helpers.NO, helpers.NO),
                                           (helpers.YES, helpers.YES)],
                                  required=False)

    def clean_repetitions_count(self):
        form_data = self.cleaned_data
        end_reason = form_data["end_reason"]
        repetitions_count = form_data.get("repetitions_count", None)

        if end_reason == PlanEndReason.AFTER_NUMBER_OF_TIMES.value and repetitions_count is None:
            raise ValidationError("Enter repetitions count")

        return repetitions_count

    def clean_start_date(self):
        form_data = self.cleaned_data
        start_date = form_data["start_date"]

        if start_date < datetime.now().date():
            raise ValidationError("Start date cannot be in the past")

        return start_date

    def clean_end_date(self):
        form_data = self.cleaned_data
        end_reason = form_data["end_reason"]
        end_date = form_data.get("end_date", None)

        if end_reason == PlanEndReason.AFTER_DATE.value and end_date is None:
            raise ValidationError("Choose end date")

        if end_date:
            start_date = form_data["start_date"]
            if end_date < start_date:
                raise ValidationError("End date sooner than start date")

        return end_date

pinecon/views.py
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.decorators import login_required
from django.forms import HiddenInput
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect

from pinecon import get_service
from pinecon.forms import TaskForm, DateForm, GroupForm, PlanForm, UserCreateForm
from pinecon.library.models.model.executor_to_task import ExecutorToTaskRelation
from pinecon.library.models.model.group import Group
from pinecon.library.models.model.group_to_task import GroupToTaskRelation
from pinecon.library.models.model.plan import PlanEndReason, Plan
from pinecon.library.models.model.task import TaskStatus, Task, TaskType
from pinecon.library.models.model.task_date import TaskDate, TaskDateType
from pinecon.library.models.model.task_to_task import TaskToTaskRelation
from pinecon.library.models.model.user import User
from pinecon.library.services.exceptions import PineconException


def login(request):
    username = request.user.username
    user = get_service().get_checked_user_by_username(username)
    get_service().current_user_id = user.user_id
    return user


def register(request):
    if request.method == "POST":
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            data = form.cleaned_data
            username = data["username"]
            password = data["password1"]
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            get_service().add_checked_user(User(user.username, user.id))
            return HttpResponseRedirect(reverse("pinecon:home"))
    else:
        form = UserCreateForm()

    context = {"form": form}
    return render(request=request, template_name="pinecon/register.html", context=context)


@login_required(login_url="/login")
def home(request):
    user = login(request)

    all_tasks = get_service().get_checked_filtered_tasks(creator_id=user.user_id, type=TaskType.SIMPLE.value)
    plans = get_service().get_checked_plan(user_id=user.user_id)
    template_tasks = get_service().get_checked_filtered_tasks(creator_id=user.user_id, type=TaskType.PLAN.value)

    plans_and_templates = list(zip(plans, template_tasks))

    groups = get_service().get_checked_filtered_groups(creator_id=user.user_id)
    executor_tasks = get_service().get_checked_filtered_tasks(executor_id=user.user_id)
    overdue_tasks = get_service().get_checked_filtered_tasks(creator_id=user.user_id,
                                                             status=TaskStatus.OVERDUE.value)
    finished_tasks = get_service().get_checked_filtered_tasks(creator_id=user.user_id,
                                                              status=TaskStatus.EXECUTED.value)

    tasks = list(set(all_tasks) - set(finished_tasks) - set(overdue_tasks))

    context = {
        "tasks": tasks,
        "plans_and_templates": plans_and_templates,
        "groups": groups,
        "executor_tasks": executor_tasks,
        "overdue_tasks": overdue_tasks,
        "finished_tasks": finished_tasks,
    }

    get_service().update_application()

    return render(request=request, template_name="pinecon/home.html", context=context)


@login_required(login_url="/login")
def create_task(request):
    user = login(request)

    if request.method == "POST":
        task_form = TaskForm(request.POST)
        if task_form.is_valid():
            data = task_form.cleaned_data

            task = get_service().add_checked_task(Task(creator_id=user.user_id,
                                                       title=data["title"],
                                                       priority=data["priority"],
                                                       description=data["description"]))

            end_date = data["end_date"]
            start_date = data["start_date"]
            if end_date and start_date:
                get_service().add_checked_date(TaskDate(task.task_id, TaskDateType.START.value, start_date))
                get_service().add_checked_date(TaskDate(task.task_id, TaskDateType.END.value, end_date))
            elif end_date:
                get_service().add_checked_date(TaskDate(task.task_id, TaskDateType.END.value, end_date))
            elif start_date:
                get_service().add_checked_date(TaskDate(task.task_id, TaskDateType.EVENT.value, start_date))

            return HttpResponseRedirect(reverse("pinecon:home"))
    else:
        task_form = TaskForm()

    task_form.fields["status"].widget = HiddenInput()

    context = {"form": task_form}
    return render(request=request, template_name="pinecon/task/create.html", context=context)


@login_required(login_url="/login")
def show_task(request, task_id):
    user = login(request)

    task = get_service().get_checked_task_by_id(task_id)

    plan = None
    if task.task_type == TaskType.PLAN.value:
        plan = get_service().get_checked_filtered_plans(task_id=task_id)[0]

    task_dates = get_service().get_all_checked_task_dates(task_id=task_id)

    task_groups = get_service().get_checked_filtered_groups(creator_id=user.user_id,
                                                       task_id=task_id)

    task_executors = get_service().get_checked_executors(task_id=task_id)
    task_creator = get_service().is_creator(executor_id=user.user_id, task_id=task_id)
    print(task_creator)
    context = {
        "task": task,
        "plan": plan,
        "dates": task_dates,
        "groups": task_groups,
        "executors": task_executors,
        "creator": task_creator
    }

    return render(request=request, template_name="pinecon/task/show.html", context=context)


@login_required(login_url="/login")
def update_task(request, task_id):
    login(request)

    task = get_service().get_checked_task_by_id(task_id)

    if request.method == 'POST':
        task_form = TaskForm(request.POST)
        if task_form.is_valid():
            data = task_form.cleaned_data

            get_service().update_checked_task(task_id=task_id,
                                              title=data["title"],
                                              priority=data["priority"],
                                              description=data["description"],
                                              status=data["status"])

            return HttpResponseRedirect(reverse('pinecon:show_task', args=(task_id,)))
    else:
        task_form = TaskForm(initial={
            "title": task.title,
            "priority": task.priority,
            "description": task.description,
            "status": task.status
        })

        task_form.fields["start_date"].widget = HiddenInput()
        task_form.fields["end_date"].widget = HiddenInput()

        if task.task_type == TaskType.PLAN.value:
            task_form.fields["status"].widget = HiddenInput()
        elif task.status == TaskStatus.CREATED.value:
            choices = [(status.value, status.value) for status in TaskStatus]
            choices.remove((TaskStatus.DEFINED.value, TaskStatus.DEFINED.value))
            task_form.fields["status"].choices = choices
        else:
            choices = [(status.value, status.value) for status in TaskStatus]
            choices.remove((TaskStatus.DEFINED.value, TaskStatus.DEFINED.value))
            choices.remove((TaskStatus.CREATED.value, TaskStatus.CREATED.value))
            task_form.fields["status"].choices = choices

    context = {
        "form": task_form,
        "task_id": task_id
    }

    return render(request=request, template_name="pinecon/task/update.html", context=context)


@login_required(login_url="/login")
def finish_task(request, task_id):
    login(request)

    get_service().update_checked_task(task_id, status='executed')

    return HttpResponseRedirect(reverse("pinecon:home"))


@login_required(login_url="/login")
def delete_task(request, task_id):
    login(request)

    get_service().delete_checked_task_with_relations(task_id)

    return HttpResponseRedirect(reverse("pinecon:home"))


@login_required(login_url="/login")
def create_subtask(request, task_id):
    context = {
        "task_id": task_id
    }

    return render(request=request, template_name="pinecon/task/subtask/create.html", context=context)


@login_required(login_url="/login")
def create_executor(request, task_id):
    login(request)

    task = get_service().get_checked_task_by_id(task_id)

    context = {
        "task": task
    }

    return render(request=request, template_name="pinecon/task/executor/create.html", context=context)


@login_required(login_url="/login")
def create_date(request, task_id):
    login(request)

    if request.method == "POST":
        date_form = DateForm(request.POST)
        if date_form.is_valid():
            try:
                data = date_form.cleaned_data

                date = get_service().add_checked_date(TaskDate(task_id=task_id,
                                                               date=data["date"],
                                                               date_type=data["date_type"]))
                return HttpResponseRedirect(reverse('pinecon:show_task', args=(date.task_id,)))

            except PineconException as exception:
                date_form.add_error('date', str(exception))

    else:
        date_form = DateForm()

    context = {
        "task_id": task_id,
        "form": date_form
    }

    return render(request=request, template_name="pinecon/date/create.html", context=context)


@login_required(login_url="/login")
def update_date(request, date_id):
    login(request)

    date = get_service().get_checked_date_by_id(date_id)

    if request.method == "POST":
        date_form = DateForm(request.POST)
        if date_form.is_valid():
            data = date_form.cleaned_data

pinecon/templates/pinecon/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Pinecon</title>
    <link rel="shortcut icon" href="{% static 'pinecon/images/pinecone.ico' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'pinecon/styles/header_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'pinecon/styles/basic_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'pinecon/styles/button_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'pinecon/styles/confirm_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'pinecon/styles/alert_style.css' %}" />

    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

    <script src="{% static 'pinecon/scripts/confirm_script.js'%}"></script>
</head>
<body>
    <div class="header">
        <div class="header-left">
            <a href="{% url 'pinecon:home'%}">Home</a>
             {% if user.is_authenticated %}
                <div class="greeting__text_header">Welcome to Pinecone, {{ user.username }}</div>
            {% else %}
                <div class="greeting__text_header">Welcome to Pinecone</div>
            {% endif %}
        </div>
        <div class="header-right">
            {% if user.is_authenticated %}
                <a href="{% url 'pinecon:create_task' %}">Add Task </a>
                <a href="{% url 'pinecon:create_plan' %}">Add Plan </a>
                <a href="{% url 'pinecon:create_group' %}"> Add Group </a>
                <a href="{% url 'pinecon:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'pinecon:login' %}"> Login </a>
                <a href="{% url 'pinecon:register' %}">Register</a>
            {% endif %}
        </div>
    </div>
    <div class="content container">
        <div class="row">
            {% block content %} {% endblock %}
        </div>
    </div>
</body>
</html>

pinecon/templates/pinecon/home.html
{% extends 'pinecon/base.html' %} {% load static %} {% block content %}
<div class="content">
    <br/> {% if not overdue_tasks and not tasks and not executor_tasks and not groups and not finished_tasks and not plans_and_templates %}
    <div class="greeting__text_small">
        <p> Now you do not have any tasks or groups. </p>
        <p> Sure, you have several urgent cases. Add them currently! </p>
    </div>
    <img class="image__pine" src="{% static 'pinecon/images/pine.png' %}"> {% endif %} {% if tasks %}
    <div class="center__wrapper">
    <button class="collapsible"> Tasks: </button>
    <div class="table__content">
        <table class="table__">
            <tr class="table__tr">
                <th class="table__th"> Title </th>
                <th class="table__th">Status</th>
                <th class="table__th">Priority</th>
                <th class="table__th"> Task Actions </th>
            </tr>
            {% for task in tasks %}
            <tr class="table__tr">
                <th class="table__td">{{ task.title }}</th>
                <th class="table__td">{{ task.status }} </th>
                <th class="table__td">{{ task.priority }} </th>
                <th class="table__td" style="width: 50%"><a class="table__td_action" href="{% url 'pinecon:show_task' task.task_id %}">show task</a>
                    <a class="table__td_action" href="{% url 'pinecon:update_task' task.task_id %}">update task</a>
                    <a class="table__td_action" href="{% url 'pinecon:finish_task' task.task_id %}">finish task</a>
                    <a class="table__td_action" href="{% url 'pinecon:delete_task' task.task_id %}">delete task</a>
                </th>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
    {% endif %} {% if executor_tasks %}
    <div class="center__wrapper">
    <button class="collapsible"> Shared Tasks: </button>
    <div class="table__content">
        <table class="table__">
            <tr class="table__tr">
                <th class="table__th"> Title </th>
                <th class="table__th">Status</th>
                <th class="table__th">Priority</th>
                <th class="table__th"> Task Actions </th>
            </tr>
            {% for task in executor_tasks %}
            <tr class="table__tr">
                <th class="table__td">{{ task.title }}</th>
                <th class="table__td">{{ task.status }} </th>
                <th class="table__td">{{ task.priority }} </th>
                <th class="table__td" style="width: 50%"><a class="table__td_action" href="{% url 'pinecon:show_task' task.task_id %}">show task</a>
                    <a class="table__td_action" href="{% url 'pinecon:update_task' task.task_id %}">update task</a>
                    <a class="table__td_action" href="{% url 'pinecon:finish_task' task.task_id %}">finish task</a>
                    <a class="table__td_action" href="{% url 'pinecon:delete_task' task.task_id %}">delete task</a>
                </th>
                </tr>
            {% endfor %}
        </table>
    </div>
    </div>
    {% endif %} {% if plans_and_templates %}
    <div class="center__wrapper">
    <button class="collapsible"> Plans: </button>
    <div class="table__content">
        <table class="table__">
            <tr class="table__tr">
                <th class="table__th"> Title </th>
                <th class="table__th">Status</th>
                <th class="table__th">Priority</th>
                <th class="table__th"> Plan Actions </th>
            </tr>
            {% for plan, template_task in plans_and_templates %}
            <tr class="table__tr">
                <th class="table__td">{{ template_task.title }}</th>
                <th class="table__td">{{ template_task.status }} </th>
                <th class="table__td">{{ template_task.priority }} </th>
                <th class="table__td" style="width: 60%"><a class="table__td_action" href="{% url 'pinecon:show_task' template_task.task_id %}">show plan</a>
                    <a class="table__td_action" href="{% url 'pinecon:update_plan' plan.plan_id %}">update plan</a>
                    <a class="table__td_action" href="{% url 'pinecon:update_task' template_task.task_id %}">update template task</a>
                    <a class="table__td_action" href="{% url 'pinecon:delete_task' template_task.task_id %}">delete plan</a>
                </th>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
    {% endif %}{% if overdue_tasks %}
    <div class="center__wrapper">
    <button class="collapsible"> Overdue Tasks: </button>
    <div class="table__content">
        <table class="table__">
            <tr class="table__tr">
                <th class="table__th"> Title </th>
                <th class="table__th">Status</th>
                <th class="table__th">Priority</th>
                <th class="table__th"> Task Actions </th>
            </tr>
            {% for task in overdue_tasks %}
            <tr class="table__tr">
                <th class="table__td">{{ task.title }}</th>
                <th class="table__td">{{ task.status }} </th>
                <th class="table__td">{{ task.priority }} </th>
                <th class="table__td" style="width: 50%"><a class="table__td_action" href="{% url 'pinecon:show_task' task.task_id %}">show task</a>
                    <a class="table__td_action" href="{% url 'pinecon:update_task' task.task_id %}">update task</a>
                    <a class="table__td_action" href="{% url 'pinecon:finish_task' task.task_id %}">finish task</a>
                    <a class="table__td_action" href="{% url 'pinecon:delete_task' task.task_id %}">delete task</a>
                </th>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
    {% endif %} {% if finished_tasks %}
    <div class="center__wrapper">
    <button class="collapsible"> Finished Tasks: </button>
    <div class="table__content">
        <table class="table__">
            <tr class="table__tr">
                <th class="table__th"> Title </th>
                <th class="table__th">Status</th>
                <th class="table__th">Priority</th>
                <th class="table__th"> Task Actions </th>
            </tr>
            {% for task in finished_tasks %}
            <tr class="table__tr">
                <th class="table__td">{{ task.title }}</th>
                <th class="table__td">{{ task.status }} </th>
                <th class="table__td">{{ task.priority }} </th>
                <th class="table__td" style="width: 50%"><a class="table__td_action" href="{% url 'pinecon:show_task' task.task_id %}">show task</a>
                    <a class="table__td_action" href="{% url 'pinecon:update_task' task.task_id %}">update task</a>
                    <a class="table__td_action" href="{% url 'pinecon:finish_task' task.task_id %}">finish task</a>
                    <a class="table__td_action" href="{% url 'pinecon:delete_task' task.task_id %}">delete task</a>
                </th>
                </tr>
            {% endfor %}
        </table>
    </div>
    </div>
    {% endif %} {% if groups %}
    <div class="center__wrapper">
    <button class="collapsible"> Groups: </button>
    <div class="table__content">
        <table class="table__">
            <tr class="table__tr">
                <th class="table__th"> Title </th>
                <th class="table__th"> Group Actions </th>
            </tr>
            {% for group in groups %}
            <tr class="table__tr">
                <th class="table__td">{{ group.title }}</th>
                <th class="table__td" style="width: 50%"><a class="table__td_action" href="{% url 'pinecon:show_group' group.group_id %}">show group</a>
                    <a class="table__td_action" href="{% url 'pinecon:update_group' group.group_id %}">update group</a>
                    <a class="table__td_action" href="{% url 'pinecon:delete_group' group.group_id %}">delete group</a>
                </th>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
    {% endif %}
</div>


<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
    } else {
      content.style.maxHeight = content.scrollHeight + "px";
    }
  });
}
</script>
{% endblock %}

pinecon/templates/pinecon/login.html
{% extends 'pinecon/base.html' %} {% block content %} {% load static %}
<body>
    {% if form.errors %}
    <div class="error__text">
        <div class="error__text_red">
            <p>Wrong input.</p>
        </div>
        <p>User with this username and password doesn't exist.</p>
        <p>Check the entered data.</p>
    </div>
    {% endif %}
    <section>
        <form method="post">
            {% csrf_token %}
            <div class="login__text">
                <p><b>User name:</b> {{ form.username }}</p>
                <p><b>Password: </b> {{ form.password }} </p>
            </div>
            <button type="submit" class="button__basic, button__login">Login</button>
        </form>

    </section>
    <img class="image__pine" src="{% static 'pinecon/images/pine.png' %}">
</body>
{% endblock %}

pinecon/templates/pinecon/register.html
{% extends 'pinecon/base.html' %} {% block content %} {% load static %}
<section>
    <form method="post" action="{% url 'pinecon:register' %}">

        {% csrf_token %} {% if form.errors %}
        <div class="error__text_red">
            <p>Wrong input.</p>
        </div>
        {% endif %}

        <table class="form__register">
            {{ form }}
        </table>

        <button type="submit" class="button__basic, button__register">Register</button>
    </form>
</section>
        <img class="image__pine" src="{% static 'pinecon/images/pine.png' %}">
{% endblock %}